version: "3.9"
services:
  app:
    container_name: time-bottle-api
    build:    
      dockerfile: Dockerfile
      target: dev
      context: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/app
      
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - time-bottle-postgres:/var/lib/postgresql/data

volumes:
  time-bottle-postgres: